<?php

namespace Steellg0ld\Museum;

use pocketmine\plugin\PluginBase;

class Plugin extends PluginBase
{
    public static $instance;

    public function onEnable()
    {
        self::$instance = $this;
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public static function getInstance(): self {
        return self::$instance;
    }
}